// src/components/Sidebar.vue
<template>
  <aside id="sidebar" class="bg-slate-900 border-r border-slate-800 flex flex-col h-full overflow-hidden w-[280px]">
    <!-- Header Logo -->
    <div class="p-6 border-b border-slate-800 flex-shrink-0">
      <div class="font-heading text-2xl font-bold tracking-tight text-white flex items-center gap-1.5">
        <span class="text-sky-400 drop-shadow-[0_0_12px_rgba(56,189,248,0.3)]">Uni</span>Report
      </div>
      <div class="text-[10px] font-bold text-slate-500 uppercase tracking-widest mt-1">
        Projeto Interdisciplinar I
      </div>
    </div>
    
    <!-- Barra de Progresso -->
    <div class="px-6 py-4 border-b border-slate-800 flex-shrink-0">
      <div class="flex justify-between text-xs font-semibold text-slate-400 mb-2">
        <span>Progresso Geral</span>
        <span class="text-sky-400">{{ store.progress }}%</span>
      </div>
      <div class="w-full h-1.5 bg-slate-950 rounded-full overflow-hidden">
        <div 
          class="h-full bg-gradient-to-r from-sky-400 to-purple-500 rounded-full transition-all duration-300"
          :style="{ width: `${store.progress}%` }"
        ></div>
      </div>
    </div>

    <!-- Navegação de Abas -->
    <nav class="flex-1 overflow-y-auto py-4">
      <ul class="space-y-0.5 px-3">
        <li 
          v-for="item in navItems" 
          :key="item.id"
          class="flex items-center px-4 py-2.5 rounded-lg text-xs font-medium cursor-pointer transition-all duration-150"
          :class="[
            item.isChecklist ? 'border-t border-slate-800/80 mt-3 pt-4 text-purple-400' : 'text-slate-400',
            store.activeSection === item.id 
              ? (item.isChecklist ? 'bg-purple-500/10 text-purple-300 font-semibold border-l-2 border-purple-500' : 'bg-sky-500/10 text-sky-400 font-semibold border-l-2 border-sky-400')
              : 'hover:bg-slate-800/30 hover:text-slate-200 border-l-2 border-transparent'
          ]"
          @click="store.activeSection = item.id"
        >
          <span class="font-mono text-[10px] opacity-60 w-5 mr-1">{{ item.num }}</span>
          {{ item.label }}
        </li>
      </ul>
    </nav>

    <!-- Rodapé com Ações -->
    <div class="p-4 border-t border-slate-800 bg-slate-950/20 flex-shrink-0 space-y-2.5">
      <!-- Botão Imprimir / PDF -->
      <button 
        @click="handlePrint" 
        class="w-full bg-sky-500 hover:bg-sky-400 text-slate-950 font-bold py-2.5 px-4 rounded-lg text-xs flex items-center justify-center gap-2 cursor-pointer shadow-lg shadow-sky-500/10 active:scale-[0.98] transition-all"
      >
        <Printer class="w-4 h-4" />
        Imprimir / PDF
      </button>

      <!-- Botão Exportar Word -->
      <button 
        @click="handleExportWord" 
        class="w-full bg-emerald-500 hover:bg-emerald-450 text-slate-950 font-bold py-2.5 px-4 rounded-lg text-xs flex items-center justify-center gap-2 cursor-pointer shadow-lg shadow-emerald-500/10 active:scale-[0.98] transition-all"
      >
        <FileDown class="w-4 h-4" />
        Exportar Word (.docx)
      </button>

      <!-- Ações Extras (Backup, Restaurar, Limpar) -->
      <div class="grid grid-cols-3 gap-1.5 pt-1">
        <button 
          @click="handleExportJson" 
          class="bg-slate-950 hover:bg-slate-800 border border-slate-800 text-[10px] font-semibold text-slate-400 hover:text-slate-200 py-1.5 rounded-md cursor-pointer transition-all"
          title="Backup JSON"
        >
          Backup
        </button>
        <button 
          @click="triggerImport" 
          class="bg-slate-950 hover:bg-slate-800 border border-slate-800 text-[10px] font-semibold text-slate-400 hover:text-slate-200 py-1.5 rounded-md cursor-pointer transition-all"
          title="Restaurar JSON"
        >
          Restaurar
        </button>
        <button 
          @click="handleClear" 
          class="bg-rose-500/10 hover:bg-rose-500 border border-rose-500/20 hover:border-rose-500 text-[10px] font-semibold text-rose-400 hover:text-white py-1.5 rounded-md cursor-pointer transition-all"
          title="Limpar Relatório"
        >
          Limpar
        </button>
      </div>

      <input 
        type="file" 
        ref="importFileInput" 
        @change="handleImportJson" 
        style="display: none" 
        accept=".json" 
      />
    </div>
  </aside>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useReportStore } from '../stores/reportStore';
import { generateWordReport } from '../services/wordGenerator';
import { Printer, FileDown } from 'lucide-vue-next';

const store = useReportStore();
const importFileInput = ref<HTMLInputElement | null>(null);

const navItems = [
  { id: 'capa', num: '00', label: 'Capa' },
  { id: 'introducao', num: '01', label: '1. Introdução' },
  { id: 'profissao', num: '02', label: '2. Profissão Escolhida' },
  { id: 'competencias', num: '03', label: '3. Competências' },
  { id: 'tecnologias', num: '04', label: '4. Tecnologias & Ferr.' },
  { id: 'ingresso', num: '05', label: '5. Formas de Ingresso' },
  { id: 'desafios', num: '06', label: '6. Desafios da Área' },
  { id: 'tendencias', num: '07', label: '7. Tendências & Futuro' },
  { id: 'relacao-curso', num: '08', label: '8. Relação com Curso' },
  { id: 'reflexao', num: '09', label: '9. Reflexão Pessoal' },
  { id: 'planejamento', num: '10', label: '10. Plan. de Carreira' },
  { id: 'financeiro', num: '11', label: '11. Ed. Financeira' },
  { id: 'conclusao', num: '12', label: '12. Conclusão' },
  { id: 'referencias', num: '13', label: '13. Referências' },
  { id: 'checklist', num: '✓', label: 'Checklist de Entrega', isChecklist: true }
];

const handlePrint = () => {
  window.print();
};

const handleExportWord = async () => {
  try {
    await generateWordReport(store.reportData);
  } catch (err) {
    console.error("Erro ao gerar documento Word:", err);
    alert("Houve um erro ao exportar para o Word. Verifique os dados.");
  }
};

const handleExportJson = () => {
  const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(store.reportData, null, 2));
  const dlAnchorElem = document.createElement('a');
  dlAnchorElem.setAttribute("href", dataStr);
  dlAnchorElem.setAttribute("download", `UniReport_Backup_${store.reportData.aluno.replace(/\s+/g, '_') || 'Estudante'}.json`);
  dlAnchorElem.click();
};

const triggerImport = () => {
  if (importFileInput.value) {
    importFileInput.value.click();
  }
};

const handleImportJson = (e: Event) => {
  const target = e.target as HTMLInputElement;
  const file = target.files?.[0];
  if (!file) return;
  
  const reader = new FileReader();
  reader.onload = async (evt) => {
    try {
      const imported = JSON.parse(evt.target?.result as string);
      await store.importBackup(imported);
      alert("Backup JSON restaurado com sucesso no Dexie!");
    } catch (err) {
      alert("Erro ao ler o backup. Certifique-se de que é um JSON válido.");
    }
  };
  reader.readAsText(file);
  target.value = ''; // limpa input
};

const handleClear = async () => {
  if (window.confirm("Atenção: Todo o progresso do relatório será apagado do Dexie (IndexedDB). Deseja continuar?")) {
    await store.clearData();
    alert("Dados reiniciados!");
  }
};
</script>

// src/components/Sidebar.jsx
import React, { useRef } from 'react';

export default function Sidebar({
    activeSection,
    setActiveSection,
    progress,
    onPrint,
    onExportJson,
    onImportJson,
    onClear
}) {
    const fileInputRef = useRef(null);

    const navItems = [
        { id: 'capa', num: '00', label: 'Capa' },
        { id: 'introducao', num: '01', label: '1. Introdução' },
        { id: 'profissao', num: '02', label: '2. Profissão Escolhida' },
        { id: 'competencias', num: '03', label: '3. Competências' },
        { id: 'tecnologias', num: '04', label: '4. Tecnologias & Ferr.' },
        { id: 'ingresso', num: '05', label: '5. Formas de Ingresso' },
        { id: 'desafios', num: '06', label: '6. Desafios da Área' },
        { id: 'tendencias', num: '07', label: '7. Tendências & Futuro' },
        { id: 'relacao-curso', num: '08', label: '8. Relação com Curso' },
        { id: 'reflexao', num: '09', label: '9. Reflexão Pessoal' },
        { id: 'planejamento', num: '10', label: '10. Plan. de Carreira' },
        { id: 'financeiro', num: '11', label: '11. Ed. Financeira' },
        { id: 'conclusao', num: '12', label: '12. Conclusão' },
        { id: 'referencias', num: '13', label: '13. Referências' },
        { id: 'checklist', num: '✓', label: 'Checklist de Entrega', isChecklist: true }
    ];

    const handleImportClick = () => {
        if (fileInputRef.current) {
            fileInputRef.current.click();
        }
    };

    const handleFileChange = (e) => {
        const file = e.target.files[0];
        if (!file) return;
        
        const reader = new FileReader();
        reader.onload = (evt) => {
            try {
                const imported = JSON.parse(evt.target.result);
                onImportJson(imported);
            } catch (err) {
                alert("Erro ao ler o arquivo JSON. Certifique-se de que é um backup válido.");
            }
        };
        reader.readAsText(file);
        // Reset file input value so same file can be uploaded again
        e.target.value = null;
    };

    return (
        <aside id="sidebar">
            <div className="sidebar-header">
                <div className="logo">
                    <span className="logo-accent">Uni</span>Report
                </div>
                <div className="subtitle">Projeto Interdisciplinar I</div>
            </div>
            
            <div className="progress-container">
                <div className="progress-label">
                    <span>Progresso Geral</span>
                    <span id="progress-percentage">{progress}%</span>
                </div>
                <div className="progress-bar-bg">
                    <div id="progress-bar-fill" style={{ width: `${progress}%` }}></div>
                </div>
            </div>

            <nav id="section-nav">
                <ul className="nav-list">
                    {navItems.map(item => (
                        <li 
                            key={item.id}
                            className={`nav-item ${item.isChecklist ? 'nav-checklist' : ''} ${activeSection === item.id ? 'active' : ''}`}
                            onClick={() => setActiveSection(item.id)}
                        >
                            <span className="nav-num">{item.num}</span> {item.label}
                        </li>
                    ))}
                </ul>
            </nav>

            <div className="sidebar-footer">
                <button id="btn-print" className="btn btn-primary" onClick={onPrint}>
                    <svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <polyline points="6 9 6 2 18 2 18 9"></polyline>
                        <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"></path>
                        <rect x="6" y="14" width="12" height="8"></rect>
                    </svg>
                    Imprimir / PDF
                </button>
                <div className="footer-actions">
                    <button className="btn btn-secondary btn-icon" onClick={onExportJson} title="Salvar Backup (JSON)">
                        Backup
                    </button>
                    <button className="btn btn-secondary btn-icon" onClick={handleImportClick} title="Restaurar Backup (JSON)">
                        Restaurar
                    </button>
                    <button className="btn btn-danger btn-icon" onClick={onClear} title="Limpar Tudo">
                        Limpar
                    </button>
                </div>
                <input 
                    type="file" 
                    ref={fileInputRef} 
                    onChange={handleFileChange} 
                    style={{ display: 'none' }} 
                    accept=".json" 
                />
            </div>
        </aside>
    );
}
